version: "3.1"
services:
    # www: #WEBSERVER
    #     build: .
    #     container_name: www
    #     ports: 
    #         - "8001:80"
    #     volumes:
    #         - ./www:/var/www/html/
    #     depends_on:
    #             - db

    wordpress:
        image: wordpress:latest
        container_name: wordpress
        ports:
            - "8010:80"
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wp_admin
            WORDPRESS_DB_PASSWORD: 12345
        depends_on:
            - db
        volumes:
            - ./wordpress:/var/www/html

    db: #DATABASE
        image: mysql
        container_name: db
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: test 
            MYSQL_DATABASE: myDb
            MYSQL_USER: wp_admin
            MYSQL_PASSWORD: 12345
        ports: 
            - "33306:3306"        
        volumes:
            - ./database:/docker-entrypoint-initdb.d
            - ./database:/etc/mysql/conf.d
            - persistent:/var/lib/mysql

    phpmyadmin: 
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - 8020:80
        environment: #logs into SQL root account
            PMA_HOST: 'db'
            PMA_PORT: '3306'
            PMA_USER: 'root'
            PMA_PASSWORD: "test"
        depends_on:
            - db

    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        hostname: prometheus
       # restart: always
        ports:
        - '8030:9090'
        volumes:
            - './config:/config'
        command:
            - '--config.file=/config/prometheus.yml' #where scraping is defined
            - '--web.enable-lifecycle'
            - '--storage.tsdb.retention.time=90d' # keep the data in 90 days

    grafana:
        image: grafana/grafana:latest
        ports:
        - 8050:3000
        restart: unless-stopped
        volumes:
        - ./grafana_database:/etc/grafana/provisioning/datasources #tell grafana where datasource file is 
        - grafana-data:/var/lib/grafana
    
    mysqlexporter:
        image: prom/mysqld-exporter:latest
        ports:
        - "9104:9104"
        environment:
        - DATA_SOURCE_NAME=root:test@(db:3306)/myDb #give exporter root login to export data 
        depends_on: 
        - db

    
volumes:
  persistent: #TODO: What does do?
  db:
  prometheus:
  grafana-data: