global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "rules.yml" #tell Prometheus where to get rules from

scrape_configs:
  #prometheus itself
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  #dummy service to generate an alert
  - job_name: services
    static_configs:
      - targets:
          - 'idonotexists:564'

  #REAL TO BE MONITORED SERVICES
  - job_name: 'mysql-server'
    static_configs:
      - targets: ['mysqlexporter:9104']

  # - job_name: 'wordpress'
  #   static_configs:
  #     -targets: 'wordpress:8010'

#  - job_name: 'grafana'
 #   static_configs:
  #    - targets: ['localhost:8050']

#  - job_name: 'phpmyadmin'
 #   static_configs:
  #    - targets: ['localhost:8020']
    